authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"

urlpatterns = [
    path("login/", views.log_in, name="log_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("log_out/", views.log_out, name="log_out"),
    path("<int:pk>/", views.profile, name="profile"),
    path("change_password/", views.change_password, name='change_password'),
]

notatky/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("authentication.urls")),
    path("", include("notes.urls")),
]

notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.all_notes, name="notes"),
    path("user_notes/", views.user_notes, name="user_notes"),
    path('create_note/', views.create_note, name='create_note'),
    path('update_note/', views.update_note, name='update_note'),
    path('delete_note/', views.delete_note, name='delete_note'),
    path("note/<int:pk>", views.details_note, name="details_note"),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash


def sign_up(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("auth:log_in")
    return render(request, "sign_up.html", {'form': form})


def log_in(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("notes:notes")
        else:
            messages.info(request,
                          "Try again! username or password is incorrect")
            context['error'] = "username or password is incorrect"
    return render(request, "log_in.html", context)


def log_out(request):
    logout(request)
    return redirect("notes:notes")


@login_required
def profile(request, pk):
    user = User.objects.get(id=pk)
    context = {"user": user}
    return render(request, "profile.html", context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            #update_session_auth_hash(request, user)
            logout(request)
            messages.success(request, 'Your password was successfully updated!')
            return redirect("auth:log_in")
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

authentication/templates/change_password.html
{% extends 'base.html' %}

{% block content %}
<center>
  <div class="white_box">
    <form method="post">
      {% csrf_token %}
      <h2>Change password</h2>
      {% for field in form %}
        <p>{{ field.label }} : {{ field }}</p>
        {% for error in field.errors %}
             <p style="color: red">{{ error }}</p>
        {% endfor %}
      {% endfor %}
      <button type="submit">Save changes</button>
    </form>
  </div>
</center>
{% endblock %}

authentication/templates/log_in.html
{% extends 'base.html' %}

{% block content %}
  <center>
    <div class="form white_box">
      <form method="POST" action="">
        {% csrf_token %}

        <h2>Login</h2>
        <p>Username:<br>
          <input type="text" name="username"></p>
        <p>Password:<br>
          <input type="password" name="password"></p>

        {% if error %}
          <p style="color: red">{{ error }}</p>
        {% endif %}

        <button type="submit"> Login </button>
        <p class="message">Don't have an account? <a href="{% url 'auth:sign_up' %}">Sign Up</a></p>
      </form>
    </div>
  </center>
{% endblock %}

authentication/templates/profile.html
{% extends 'base.html' %}

{%  block content %}
    <center>
        <div class="white_box">
            <h2>Profile</h2>
            <p>Username : {{ user.username }}</p>
            <p>Date joined : {{ user.date_joined }}</p>
            <button><a href="{% url 'auth:change_password' %}">Change password</a></button>
        </div>
    </center>
{% endblock %}

authentication/templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
  <center>
    <div class="white_box">
    <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Sign up</button>
      </form>
    </div>
  </center>
{% endblock %}