authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"

urlpatterns = [
    path("login/", views.log_in, name="log_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("log_out/", views.log_out, name="log_out"),
    path("<int:pk>/", views.profile, name="profile"),
    path("change_password/", views.change_password, name='change_password'),
]

notatky/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("authentication.urls")),
    path("", include("notes.urls")),
]

notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.all_notes, name="notes"),
    path("user_notes/", views.user_notes, name="user_notes"),
    path('create_note/', views.create_note, name='create_note'),
    path('update_note/', views.update_note, name='update_note'),
    path('delete_note/', views.delete_note, name='delete_note'),
    path("note/<int:pk>", views.details_note, name="details_note"),
]

notatky/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">

    {% block header %}
    {% endblock %}

    <title>Notes</title>

  </head>
  <body>

  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}

  </body>
</html>

notatky/templates/navbar.html
{%  block content %}
<div class="navbar">
  <a href="{% url 'notes:notes' %}">Записки</a>
  {% if user.is_authenticated %}
  <a href="{% url 'notes:user_notes' %}">Мої записки</a>
  <a href="{% url 'auth:log_out' %}" style="float:right">Вийти</a>
  <a href="{% url 'auth:profile' user.id %}" style="float:right">{{ user.username }}</a>
  {% else %}
  <a href="{% url 'auth:log_in' %}" style="float:right">Увійти</a>
  {% endif %}
</div>
{% endblock %}