notatky/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("authentication.urls")),
    path("", include("notes.urls")),
]

notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.all_notes, name="notes"),
    path("user_notes/", views.user_notes, name="user_notes"),
    path('create_note/', views.create_note, name='create_note'),
    path('update_note/', views.update_note, name='update_note'),
    path('delete_note/', views.delete_note, name='delete_note'),
    path("note/<int:pk>", views.details_note, name="details_note"),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import random


class Note(models.Model):
    title = models.CharField(max_length=300, default='')
    content = models.TextField(default='')

    # store note position
    left = models.CharField(max_length=7, default='35vw')
    top = models.CharField(max_length=7, default='37h')

    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.title


    def get_title_id(self):
        return f'title_{self.id}'


    def get_content_id(self):
        return f'content_{self.id}'


    def get_footer_id(self):
        return f'footer_{self.id}'

    def when_published(self):
        now = timezone.now()
        since = now - self.creation_date
        days = since.days
        seconds = since.seconds

        if days == 0:
            if int(seconds / 3600) == 1:
                return f"{int(seconds / 3600)} hour ago"
            elif seconds >= 3600:
                return f"{int(seconds / 3600)} hours ago"
            elif int(seconds / 60) == 1:
                return f"{int(seconds / 60)} minute ago"
            else:
                return f"{int(seconds / 60)} minutes ago"
        elif days == 1:
            return f"{days} day ago"
        else:
            return f"{days} days ago"


    def get_edits(self):
        return self.edit_set.all()


    def get_last_edit(self):
        edits = self.get_edits()

        #if edits:
        #    return edits.order_by('-creation_date')[0]

        #edits = self.get_edits()

        if edits:
            last_edit = edits[0]
            for edit in edits:
                if edit.creation_date > last_edit.creation_date:
                    last_edit = edit
            return last_edit


    def get_save_alert_id(self):
        return f'save_alert_{self.id}'


    def html_users_edits(self):
        d = {}
        edits = self.get_edits()
        if edits:
            for edit in edits:
                if edit.author not in d:
                    d[edit.author] = 1
                else:
                    d[edit.author] += 1
        return [f'{author} : {d[author]} upd' for author in d]


class Edit(models.Model):
    title = models.CharField(max_length=300)
    content = models.TextField()
    note = models.ForeignKey(
        Note, on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)

    def when_published(self):
        now = timezone.now()
        since = now - self.creation_date
        days = since.days
        seconds = since.seconds

        if days == 0:
            if int(seconds/3600) == 1:
                return f"{int(seconds / 3600)} hour ago"
            elif seconds >= 3600:
                return f"{int(seconds/3600)} hours ago"
            elif int(seconds / 60) == 1:
                return f"{int(seconds / 60)} minute ago"
            else:
                return f"{int(seconds / 60)} minutes ago"
        elif days == 1:
            return f"{days} day ago"
        else:
            return f"{days} days ago"

    def get_position(self):
        edits = self.note.get_edits().order_by('-creation_date')

        if edits:
            i = 0
            for edit in edits:
                if edit.id == self.id:

                    row = i // 4
                    col = i % 4

                    xran = 5*random.random()
                    yran = 1 * random.random()

                    return f'left:{3 + col*23 + xran}%; ' \
                           f'top:{5 + row*2 + i*4 + yran}rem;'
                i += 1

notes/views.py
from django.shortcuts import render
from .models import Edit, Note
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


# get all notes
def all_notes(request):
    context = {'notes': Note.objects.all(),
               'user': request.user,
               'only_user': False,}
    return render(request, "all_notes.html", context)


# get only user notes
@login_required
def user_notes(request):
    context = {'notes': Note.objects.all(),
               'user': request.user,
               'only_user': True}
    return render(request, "all_notes.html", context)


@login_required
def create_note(request):
    if is_ajax(request) and request.method == "POST":

        note = Note(author=User.objects.get(username=request.user))
        note.save()

        # return the note.id to JS
        response = {
            'id': note.id
        }

        return JsonResponse(response)


@login_required
def update_note(request):
    if is_ajax(request) and request.method == "POST":

        # collect data
        id = request.POST['id']
        title, content = request.POST['title'], request.POST['content']
        left, top = request.POST['left'], request.POST['top']

        # update note
        note = Note.objects.get(id=id)

        if note.title == title and note.content == content:
            return JsonResponse({'saved': False, 'message': f'note {id} wasn\'t changed'})
        else:
            note.title, note.content = title, content
            note.left, note.top = left, top
            note.save()

        # create edit instance
        edit = Edit(author=User.objects.get(username=request.user),
                    title=title,
                    content=content,
                    note=note)
        edit.save()

        return JsonResponse({'saved': True, 'message': f'note {id} successfully updated'})


@login_required
def delete_note(request):
    if is_ajax(request) and request.method == "POST":

        id = request.POST['id']
        note = Note.objects.get(id=id)
        note.delete()

        return JsonResponse({'message': f'note {id} successfully deleted'})


@login_required
def details_note(request, pk):
    note = Note.objects.get(id=pk)
    edits = note.get_edits()
    context = {
        "edits": edits,
        "note": note
    }
    return render(request, "details_note.html", context)

notes/templates/all_notes.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'note.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="https://adrianotiger.github.io/web-esheep/dist/esheep.min.js"></script>
    <script src="{% static 'note.js' %}"></script>
{% endblock %}


{%  block content %}

        <script>
          const sheep = new eSheep();
          sheep.Start();
        </script>

        {% csrf_token%}
        {% if user.is_authenticated %}
                <button class="button" id="createsticky">Stick it!</button>
        {% endif %}

        <div id="stickies-container">
                {% for note in notes %}
                        {% if not only_user or user == note.author %}
                                <div id={{ note.id }} class="drag sticky"
                                     style="left:{{ note.left }}; top:{{ note.top }}">

                                        <div id={{ note.get_save_alert_id }} class="save_alert">
                                        </div>

                                        <h3><input type="text" name="stickytitle"
                                                   id={{ note.get_title_id }} value={{ note.title }}></h3>

                                        <p><textarea name="stickytext" id={{ note.get_content_id }}
                                                     cols="24" rows="10">{{ note.content }}</textarea></p>

                                        {% if note.author == user %}
                                                <span class="deletesticky">&times;</span>
                                        {% endif %}

                                        {% if user.is_authenticated %}
                                                <span class="savesticky">&#10003;</span>
                                        {% endif %}

                                        {% if note.get_last_edit %}
                                        <a href="{% url 'notes:details_note' note.id %}" style="text-decoration:none;">
                                                <div id={{ note.get_footer_id }}, class="update_footer">
                                                        {% if user == note.get_last_edit.author %}
                                                        <span>upd: {{ note.get_last_edit.when_published }} by you</span>
                                                        {% else %}
                                                        <span>upd: {{ note.get_last_edit.when_published }} by {{ note.get_last_edit.author }}</span>
                                                        {% endif %}
                                                </div>
                                        </a>
                                        {% endif %}
                                </div>
                        {% else %}

                         <div id={{ note.id }} class="grass_border"
                                    style="left:{{ note.left }}; top:{{ note.top }}">
                         </div>

                        {% endif %}
                {% endfor %}
        </div>

{% endblock %}

notes/templates/details_note.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'note.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="https://adrianotiger.github.io/web-esheep/dist/esheep.min.js"></script>
    <script src="{% static 'note.js' %}"></script>
{% endblock %}


{%  block content %}

<center>
    <h3>Chronicle of note №{{ note.id }}</h3>
    {% if note.author == user %}
        <p>created  {{ note.when_published }} by you</p>
    {% else %}
        <p>created  {{ note.when_published }} by {{ note.author }}</p>
    {% endif %}
</center>

<div class="users_edits">
    {% for stat in note.html_users_edits %}
        {{ stat }}<br>
    {% endfor %}
</div>

<div class="container-flexy">
{% for edit in edits|dictsortreversed:"creation_date" %}
    <div class="sticky-flexy" style="{{ edit.get_position }}">

        <h3>{{ edit.title }}</h3>

        <p>{{ edit.content }}</p>

        <div class="sticky_update_footer">
                {% if edit.author == user %}
                    upd:  {{ edit.when_published }} by you
                {% else %}
                    upd:  {{ edit.when_published }} by {{ edit.author }}
                {% endif %}
        </div>

    </div>
{% endfor %}
</div>

{% endblock %}